export const shopCategories = [
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "electronics", label: "Electronics" },
  { value: "groceries", label: "Groceries" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "home_decor", label: "Home Decor" },
  { value: "furniture", label: "Furniture" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "toys", label: "Toys & Games" },
  { value: "books", label: "Books & Stationery" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "footwear", label: "Footwear" },
  { value: "pharmacy", label: "Pharmacy & Health" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "baby_products", label: "Baby Products" },
  { value: "automotive", label: "Automotive" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "garden", label: "Garden & Plants" },
  { value: "music", label: "Music & Instruments" },
  { value: "office_supplies", label: "Office Supplies" },
  { value: "gift_shop", label: "Gift Shop" },
  { value: "mobile_phones", label: "Mobile Phones & Accessories" },
  { value: "computer_store", label: "Computers & Accessories" },
  { value: "supermarket", label: "Supermarket" },
  { value: "convenience_store", label: "Convenience Store" },
  { value: "bakery", label: "Bakery" },
  { value: "butcher", label: "Butcher" },
  { value: "florist", label: "Florist" },
  { value: "optician", label: "Optician" },
  { value: "stationery", label: "Stationery" },
  { value: "cosmetics", label: "Cosmetics" },
  { value: "wine_spirits", label: "Wine & Spirits" },
  { value: "watch_store", label: "Watch Store" },
  { value: "art_gallery", label: "Art Gallery" },
  { value: "hobby_store", label: "Hobby Store" },
  { value: "travel_agency", label: "Travel Agency" },
  { value: "photo_store", label: "Photo Store" },
  { value: "video_games", label: "Video Games" },
  { value: "lingerie", label: "Lingerie" },
  { value: "outdoor_gear", label: "Outdoor Gear" },
  { value: "party_supplies", label: "Party Supplies" },
];
