export const countries = [
  { code: "AU", name: "Australia", dial_code: "+61" },
  { code: "AT", name: "Austria", dial_code: "+43" },
  { code: "BE", name: "Belgium", dial_code: "+32" },
  { code: "BR", name: "Brazil", dial_code: "+55" },
  { code: "BG", name: "Bulgaria", dial_code: "+359" },
  { code: "CA", name: "Canada", dial_code: "+1" },
  { code: "HR", name: "Croatia", dial_code: "+385" },
  { code: "CY", name: "Cyprus", dial_code: "+357" },
  { code: "CZ", name: "Czechia", dial_code: "+420" },
  { code: "DK", name: "Denmark", dial_code: "+45" },
  { code: "EE", name: "Estonia", dial_code: "+372" },
  { code: "FI", name: "Finland", dial_code: "+358" },
  { code: "FR", name: "France", dial_code: "+33" },
  { code: "DE", name: "Germany", dial_code: "+49" },
  { code: "GR", name: "Greece", dial_code: "+30" },
  { code: "HK", name: "Hong Kong", dial_code: "+852" },
  { code: "HU", name: "Hungary", dial_code: "+36" },
  { code: "IN", name: "India", dial_code: "+91" },
  { code: "IE", name: "Ireland", dial_code: "+353" },
  { code: "IT", name: "Italy", dial_code: "+39" },
  { code: "JP", name: "Japan", dial_code: "+81" },
  { code: "LV", name: "Latvia", dial_code: "+371" },
  { code: "LI", name: "Liechtenstein", dial_code: "+423" },
  { code: "LT", name: "Lithuania", dial_code: "+370" },
  { code: "LU", name: "Luxembourg", dial_code: "+352" },
  { code: "MY", name: "Malaysia", dial_code: "+60" },
  { code: "MT", name: "Malta", dial_code: "+356" },
  { code: "MX", name: "Mexico", dial_code: "+52" },
  { code: "NL", name: "Netherlands", dial_code: "+31" },
  { code: "NZ", name: "New Zealand", dial_code: "+64" },
  { code: "NO", name: "Norway", dial_code: "+47" },
  { code: "PL", name: "Poland", dial_code: "+48" },
  { code: "PT", name: "Portugal", dial_code: "+351" },
  { code: "RO", name: "Romania", dial_code: "+40" },
  { code: "SG", name: "Singapore", dial_code: "+65" },
  { code: "SK", name: "Slovakia", dial_code: "+421" },
  { code: "SI", name: "Slovenia", dial_code: "+386" },
  { code: "ES", name: "Spain", dial_code: "+34" },
  { code: "SE", name: "Sweden", dial_code: "+46" },
  { code: "CH", name: "Switzerland", dial_code: "+41" },
  { code: "AE", name: "United Arab Emirates", dial_code: "+971" },
  { code: "GB", name: "United Kingdom", dial_code: "+44" },
  { code: "US", name: "United States", dial_code: "+1" },
];
